// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Harital/shopping-cart/internal/core/ports (interfaces: CartItemsRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/CartItemsRepository_mock.go -package=mocks . CartItemsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Harital/shopping-cart/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCartItemsRepository is a mock of CartItemsRepository interface.
type MockCartItemsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartItemsRepositoryMockRecorder
}

// MockCartItemsRepositoryMockRecorder is the mock recorder for MockCartItemsRepository.
type MockCartItemsRepositoryMockRecorder struct {
	mock *MockCartItemsRepository
}

// NewMockCartItemsRepository creates a new mock instance.
func NewMockCartItemsRepository(ctrl *gomock.Controller) *MockCartItemsRepository {
	mock := &MockCartItemsRepository{ctrl: ctrl}
	mock.recorder = &MockCartItemsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartItemsRepository) EXPECT() *MockCartItemsRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCartItemsRepository) Add(arg0 context.Context, arg1 model.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCartItemsRepositoryMockRecorder) Add(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCartItemsRepository)(nil).Add), arg0, arg1)
}

// Get mocks base method.
func (m *MockCartItemsRepository) Get(arg0 context.Context) ([]model.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]model.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCartItemsRepositoryMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCartItemsRepository)(nil).Get), arg0)
}

// SetReservationId mocks base method.
func (m *MockCartItemsRepository) SetReservationId(arg0 model.CartItem, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReservationId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReservationId indicates an expected call of SetReservationId.
func (mr *MockCartItemsRepositoryMockRecorder) SetReservationId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReservationId", reflect.TypeOf((*MockCartItemsRepository)(nil).SetReservationId), arg0, arg1)
}
