# The swagger previewer extension should be installed in the dev environment
# Press ctrl + mays + P and select "preview swagger"
openapi: 3.0.3
info:
  title: Shopping cart public api
  description: |-
    API definition for the shopping cart exercise

  contact:
    name: Albert Vélez
    email: albert.velez.ortiz@gmail.com

  version: 1.0.0

tags:
  - name: Order management
    description: order related operations
    
paths:
  /shopping-cart/v1/items:
    get:
      tags: 
        - Order management
      summary: gets the items in the shopping cart
      operationId: getItemsFromCart
      responses:
        '200': 
          description: retrieval ok. Items returned in the response
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/shoppingCartItemsResponse'
        '401':
          description: unauthorized. Not implemented
        '500':
          description: internal server error. 
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/errorResponse'
    post:
      tags: 
        - Order management
      summary: adds a new item to the cart
      description: if the item is already added, it will sum the quantity. Name is not really necessary. Only id.
      operationId: addItemToCart
      requestBody:
        content:
          application/json:
            schema:
            # Added item in the json so the request can be expandible. It´s "free" and ensure backwards compatibility
              $ref: '#/components/schemas/shoppingCartItemRequest'
      responses:
        '202':
          description: Items added. Reservatin id processed in background
          # We could reserve 200 to a fully completed operation, where the reservation id is retrieved
        '401':
          description: unauthorized. Not implemented
        '400':
          description: bad request. Query is not well formed.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: internal server error. 
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/errorResponse'
        
  
    
components:
  schemas:
    shoppingCartItem:
      type: object
      properties:
        id: 
          type: string
          example: "1"
          description: id of the item. String to make it agnostic to the storage
        name: 
          type: string
          example: fancy pants
        quantity:
          type: integer
          example: 1
        reservationId: 
         type: string
         example: 1234

    shoppingCartItemRequest:
      type: object
      properties: 
        item: 
          $ref: '#/components/schemas/shoppingCartItem'

    shoppingCartItemsResponse:
      type: object
      properties:
        version:
          type: string
          description: version of the response. It does not hurt and could potentially be used to differently parsing 2 different versions
          example: 1.0.0
        items:
          type: array
          items: 
            $ref: '#/components/schemas/shoppingCartItem'
            
    errorResponse:
      required:
        - version
      type: object
      properties:
        version:
          type: string
        message:
          type: string
          example: the cause of the error.
